# Generated by Django 5.0.6 on 2024-06-26 04:50

import auctions.models
import auctions.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_image', models.ImageField(upload_to=auctions.models.auction_image_path)),
                ('type', models.CharField(choices=[('PB', 'Public'), ('PR', 'Private'), ('OC', 'Only Contacts')], default='PB', max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('starter_price', models.PositiveIntegerField(default=0)),
                ('auction_price', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to=auctions.models.additional_field_icon_path)),
                ('title', models.CharField(max_length=30)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_fields', to='auctions.auction')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_add_admin', models.BooleanField(default=False)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='permissions',
            field=models.ManyToManyField(through='auctions.AuctionUserPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=auctions.models.auction_additional_image_path)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_fields', to='auctions.auction')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='user_like',
            field=models.ManyToManyField(related_name='liked_auctions', through='auctions.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ParticipantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='participants',
            field=models.ManyToManyField(related_name='participanted_auctions', through='auctions.ParticipantData', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VideoField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to=auctions.models.auction_additional_video_path, validators=[auctions.validators.validate_video_file_extension])),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_fields', to='auctions.auction')),
            ],
        ),
        migrations.CreateModel(
            name='Watchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.PositiveIntegerField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='user_watchers',
            field=models.ManyToManyField(related_name='watched_auctions', through='auctions.Watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
