# Generated by Django 5.0.6 on 2024-07-03 14:47

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='limit_by_clicks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='limit_by_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=24, unique=True),
        ),
    ]
