# Generated by Django 5.0.6 on 2024-07-11 10:16

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_generator', '0003_alter_link_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=24, unique=True),
        ),
    ]
