# Generated by Django 5.0.6 on 2024-08-02 16:07

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_additionalfield_auction_and_more'),
        ('link_generator', '0005_alter_link_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction', verbose_name='Auction'),
        ),
        migrations.AlterField(
            model_name='link',
            name='clicks',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Clicks'),
        ),
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='link',
            name='limit_by_clicks',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Limit By Clicks'),
        ),
        migrations.AlterField(
            model_name='link',
            name='limit_by_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Limit By Time'),
        ),
        migrations.AlterField(
            model_name='link',
            name='path',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=24, unique=True, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='link',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
