# Generated by Django 5.0.6 on 2024-07-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ST', 'STRIPE')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
